[tool.black]
line-length = 88
target-version = ['py311']
include = '\.pyi?$'
extend-exclude = '''
/(
  # directories
  \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.pytest_cache
  | \.venv
  | venv
  | _build
  | buck-out
  | build
  | dist
  | \.databricks
)/
'''

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 88
