name: CI - Test and Validate

on:
    pull_request:
        branches: [main, develop]
    push:
        branches: [develop]

jobs:
    test:
        runs-on: ubuntu-latest
        environment: development

        steps:
        - uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.11'

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements-dev.txt
            pip install databricks-cli

        - name: Run tests
          run: |
            pytest tests/ -v
        
        - name: Lint code
          run: |
            flake8 src/ --max-line-length=88 --extend-ignore=E203,W503
            black --check src/
        
        - name: Validate Databricks Bundle
          env:
            DATABRICKS_HOST: ${{ secrets.DATABRICKS_DEV_HOST }}
            DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_DEV_TOKEN }}
          run: |
            # Validate the bundle configuration
            databricks bundle validate --target dev